name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  docker-image: wikibot-canary
  docker-tags: v1-alpha ${{ github.sha }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Install DockerSlim
        id: install-docker-slim
        run: |
          curl -L -O https://github.com/docker-slim/docker-slim/releases/latest/download/dist_linux.tar.gz
          tar -zxvf dist_linux.tar.gz

      - name: Build Container
        id: build-image
        run: |
          ./dist_linux/docker-slim build ./docker/Dockerfile --dockerfile-context $GITHUB_WORKSPACE --tags ${{ env.docker-image }}:${{ env.docker-tags }} --http-probe-off -exec "Continue" --continue-after exec

      - name: Push To ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.docker-image }}
          tags: ${{ env.docker-tags }}
          registry: ghcr.io/shitcorp
          username: shitcorp
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
